AlibabaPAI/llumnix

benchmark/benchmark_serving.py, llumnix/backends/vllm/executor.py, llumnix/backends/vllm/llm_engine.py, llumnix/entrypoints/vllm/api_server.py
1. Fix typo in benchmark_serving.py.
2. Improve api server throughput.
3. Record inference latency in executor to improve simulator accuracy.
4. Fix TP hang by changing worker max_concurrency to 2. 
5. Use real profiling latency data by default(rather than estimated data) to improve simulator accuracy.
=> [Misc] Improve simulator&&api_server performance

llumnix/backends/backend_interface.py, llumnix/backends/vllm/llm_engine.py, llumnix/llumlet/llumlet.py
Refactor `Llumlet`, move functions and data such as `run_engine_loop,` `step,` and `free_request_states` to the `LLMEngineLlumnix`. There is no longer any need to make assumptions about step returns and loop ways of the backend engine.
=> [Refactor] Refactor llumlet to better adapt to different backend engines

llumnix/backends/profiling.py, llumnix/backends/vllm/executor.py, llumnix/backends/vllm/scheduler.py, llumnix/entrypoints/llumnix_utils.py, llumnix/entrypoints/vllm/api_server.py, llumnix/global_scheduler/scale_scheduler.py, llumnix/llumlet/local_migration_scheduler.py, llumnix/llumlet/migration_coordinator.py
Change TODO id from alibaba id to github id.
=> [Misc] Change TODO id

.gitmodules, Makefile, benchmark/benchmark_serving.py, docs/Arguments.md, docs/Quickstart.md, llumnix/arg_utils.py, llumnix/backends/migration_backend_interface.py, llumnix/backends/utils.py, llumnix/backends/vllm/executor.py, llumnix/backends/vllm/llm_engine.py, llumnix/backends/vllm/migration_backend.py, llumnix/backends/vllm/simulator.py, llumnix/backends/vllm/worker.py, llumnix/config.py, llumnix/entrypoints/llumnix_utils.py, llumnix/entrypoints/vllm/api_server.py, llumnix/global_scheduler/dispatch_scheduler.py, llumnix/llm_engine_manager.py, llumnix/llumlet/llumlet.py, requirements.txt, tools/pygloo_install.sh
1. add gloo and nccl migration backend support for kv cache transfer
2. optimize kv-cache transfer with layer-wise pipeline
3. add elastic support for gloo and nccl migration backend
=> [Core] Add Gloo and NCCL migration backends with elastic support

benchmark/benchmark_serving.py, docs/Arguments.md, llumnix/arg_utils.py, llumnix/backends/vllm/llm_engine.py, llumnix/backends/vllm/scheduler.py, llumnix/llm_engine_manager.py
Previously, we updated the instance info of the engine after each step. Instance info is used by the global scheduler to get the instance's memory usage, etc. However, the actual time point of instance memory update occurs when the scheduler schedules the requests before each step. So, instead of updating the instance info after each step, this pr implements the scheduler to call back the engine to update instance info right after scheduling requests. With this change, the global scheduler can get more timely instance info, which could benefit dynamic scheduling.
Also, I fix some arguments description and TODOs passingly in this pr.
=> [Misc] Update instance info of engine in a timely manner

.pylintrc, Makefile, llumnix/llm_engine_manager.py, tests/backends/vllm/test_llm_engine.py, tests/backends/vllm/test_migration.py, tests/backends/vllm/test_migration_backend.py, tests/backends/vllm/test_scheduler.py, tests/backends/vllm/test_worker.py, tests/entrypoints/vllm/api_server_manager.py, tests/entrypoints/vllm/test_api_server.py, tests/global_scheduler/test_llm_engine_manager.py, tests/llumlet/test_migration_coordinator.py
1. Add test for migration backend and worker
2. install pylint-pytest for tests folder
3. catch the error if the gloo_queue is not created when rebuild_migrate_backend
=> [CI] Add test for migration backend and worker

llumnix/backends/vllm/llm_engine.py, llumnix/entrypoints/vllm/api_server.py, llumnix/llm_engine_manager.py
Currently, when Llumnix finds manager/instance unavailable when generating a request, the request is regenerated because Llumnix cannot know whether the request is successfully dispatched into instance. However, this could bring duplicate requests in instances. Duplicate requests mean that two requests will continuously output to the user at the same time, which is quite terrible behavior. However, duplicate requests are hard to detect and intercept by api server unless comparing the output prompts of requests. But this will cause innegligible cost in the critical path of processing outputs. Considering the low possibility of manager/instance unavailable when generating a request, we choose not to re-generate the request, and user can find the request failed when timeout, which is …
=> [Failover][BugFix] Fix duplicate requests caused by failover

Makefile, llumnix/backends/vllm/llm_engine.py, llumnix/backends/vllm/scheduler.py, llumnix/backends/vllm/sequence.py, tests/backends/vllm/test_llm_engine.py, tests/backends/vllm/utils.py
Found some request outputs are not written back to the api server. This is caused by server_infos of ignored_seq_groups are not added into the server_info_list.
1. Fix the request output loss through adding server_infos of ignored_seq_groups into server_info_list
2. Fix missing scheduler lock when changing waiting queue in add_request of llm_engine
=> [BugFix] Fix request output loss during putting back to the api server

llumnix/llm_engine_manager.py
Previously, Llumnix starts post process of migration in manger after all migration tasks done (after asyncio.gather). In this pr, we implement post process of migration in manager through asynchronous task done callback. After this pr, each migration task can be post processed in manager immediately after the migration done.
=> [Misc] Implement post process of migration through asynchronous task done callback

.github/workflows/bench_test.yml, .github/workflows/e2e_test.yml, .github/workflows/migration_test.yml, .github/workflows/offline_inference.yml, .github/workflows/pylint.yml, .github/workflows/unit_test.yml, .github/workflows/whl_build.yml, llumnix/backends/backend_interface.py, llumnix/backends/vllm/llm_engine.py, llumnix/backends/vllm/simulator.py, llumnix/backends/vllm/worker.py, llumnix/llm_engine_manager.py, llumnix/llumlet/llumlet.py, llumnix/utils.py, tests/unit_test/llumlet/test_engine_step_exception.py, tests/unit_test/llumlet/test_local_migration_scheduler.py
When an error occurs in the engine.step thread, the main thread will not exit.
In the pr, catch the exception and exit the main thread to release the resources.
=> [Misc] Ensure Llumlet main thread exits on Engine.Step errors

.github/workflows/bench_test.yml, .github/workflows/e2e_test.yml, .github/workflows/migration_test.yml, .github/workflows/offline_inference.yml, .github/workflows/pylint.yml, .github/workflows/unit_test.yml, tests/e2e_test/test_migration.py
Previously, cancel_previous_workflows ran on self-hosted runners, but all workflows were executed in a queued manner on the self-hosted environment, which prevented cancel_previous_workflows from canceling workflows submitted on the current branch. Changing it to ubuntu-latest can resolve this issue.
=> [CI] move cancel_previous_workflows to ubuntu-latest

llumnix/backends/vllm/llm_engine.py, llumnix/entrypoints/vllm/api_server.py
1. Default value cannot take effect for CLI parameters with store_true
2. change num_cpu to 0 for async_put_queue_actor as the pg for llumlet. only has 1 cpu
=> [Bugfix] Change num_cpu to 0 for async_put_queue_actor

Makefile, llumnix/llm_engine_manager.py, tests/e2e_test/test_bench.py, tests/e2e_test/test_e2e.py, tests/e2e_test/test_migration.py, tools/migration_test.sh
1. Add launch modes test to ensure that llumnix can launch correctly under different '--disable-init-instance-by-manager' and '--disable-fixed-node-init-instance' combinations.
2. Add available blocks test to ensure that migrations do not cause kv cache blocks leaking.
=> [CI] Add launch modes and available blocks tests in e2e test

llumnix/global_scheduler/global_scheduler.py, llumnix/global_scheduler/migration_filter.py, llumnix/global_scheduler/migration_policy.py, llumnix/global_scheduler/migration_scheduler.py, llumnix/internal_config.py, llumnix/llm_engine_manager.py, tests/unit_test/global_scheduler/test_migration_scheduler.py
The current migration logic is somewhat confusing, as the filter contains the logic for sorting instances by load. In the refactored logic, we aim to adhere to the Single Responsibility Principle as much as possible:
1. The MigrationFilter will only handle filtering-related logic, with specific filter strategies determined by pair_migration_type.
2. The PairMigrationPolicy will process the source and destination instance information after filtering.
=> [Refactor] refactor migration scheduler

docs/Quickstart.md, docs/Supported_Models.md, setup.py
1. Change vllm to 0.6.3.post1 in docs.
2. Remove python 3.8 support(during to ray nightly version requirement)
=> [Doc][Setup] Change python version and vllm version

.github/workflows/pylint.yml, Makefile, docs/Quickstart.md, tools/docker/Dockerfile.vllm, tools/image_build.sh, tools/run_test.sh
usage:
git clone https://github.com/AlibabaPAI/llumnix.git
[Optional] git checkout <branch_name>  or git checkout <commit_id>
./tools/image_build.sh
time cost:
The vllm Docker image build will be completed within 15 minutes.
=> [Docker] Add docker file for vllm

.github/workflows/bench_test.yml, Makefile, llumnix/arg_utils.py, llumnix/backends/vllm/llm_engine.py, llumnix/backends/vllm/sim_executor.py, llumnix/backends/vllm/utils.py, llumnix/entrypoints/vllm/arg_utils.py, tests/unit_test/backends/vllm/test_migration.py, tests/unit_test/backends/vllm/test_simulator.py
This pr is based on the [pr](https://github.com/AlibabaPAI/llumnix/pull/110) contributed by @Ronniexie, addressing the [issue](https://github.com/AlibabaPAI/llumnix/issues/100). 
Currenly, async output processing is only supported when disabling migration. We are implementing new live migration codes supporting async output processing and use_ray_spmd_worker.
=> [Core] Support async output processing when disabling migration

llumnix/manager.py, tests/conftest.py, tests/unit_test/global_scheduler/test_manager.py
Previously, wait remote call will take 2ms. So the throughput of generate is around 512 req/s. In this pr, without waiting ray remote call, generate will only take under 1ms. So the throughput of generate is above 1024 req/s.
=> [Scalability] Not wait ray remote call in generate and abort to improve throughput

Makefile, docs/Arguments.md, llumnix/arg_utils.py, llumnix/backends/utils.py, llumnix/backends/vllm/utils.py, llumnix/config/default.py, llumnix/entrypoints/bladellm/api_server.py, llumnix/entrypoints/vllm/arg_utils.py, llumnix/entrypoints/vllm/register_service.py, llumnix/entrypoints/vllm/serve.py, llumnix/global_scheduler/migration_filter.py, llumnix/internal_config.py, llumnix/launcher.py, llumnix/manager.py, llumnix/utils.py, tests/conftest.py, tests/e2e_test/test_bench.py, tests/e2e_test/test_migration.py, tests/e2e_test/utils.py, tests/unit_test/entrypoints/vllm/api_server_actor.py, tests/unit_test/global_scheduler/test_manager.py, tests/unit_test/test_utils.py
For engine based prefill decode disaggregation in global launch mode, after this pr, user can first run register_args.py twice to register engine args for prefill and decode type engine, and then user can run serve.py to launch based prefill decode disaggregation in global launch mode.
Test command
```bash
python llumnix/entrypoints/vllm/save_engine_args.py --engine-type prefill --save-path test --save-key test --worker-use-ray
python llumnix/entrypoints/vllm/save_engine_args.py --engine-type decode --save-path test --save-key test --worker-use-ray
python llumnix/entrypoints/vllm/serve.py --enable-pd-disagg --worker-use-ray --load-engine-args-from-storage --load-engine-args-path ./test/test
```
=> [PDD][Deployment] Support engine based prefill decode disaggregation in global launch mode

llumnix/entrypoints/api_server_actor.py, llumnix/entrypoints/bladellm/api_server_actor.py
If host in launch parameter is '127.0.0.1' or '0.0.0.0', llumnix will not use local ip as entrypoint host.
=> [Deployment] Support eas deploy

docs/Arguments.md, llumnix/arg_utils.py, llumnix/backends/bladellm/llm_engine.py, llumnix/config/default.py, llumnix/entrypoints/bladellm/api_server.py, llumnix/entrypoints/bladellm/arg_utils.py, llumnix/global_scheduler/dispatch_scheduler.py, llumnix/global_scheduler/global_scheduler.py, llumnix/global_scheduler/migration_scheduler.py, llumnix/global_scheduler/scaling_scheduler.py, llumnix/llumlet/llumlet.py, llumnix/manager.py, llumnix/scaler.py, tests/unit_test/global_scheduler/test_dispatch_scheduler.py, tests/unit_test/global_scheduler/test_global_scheduler.py, tests/unit_test/global_scheduler/test_manager.py, tests/unit_test/global_scheduler/test_migration_scheduler.py
1. support dispatch decode instance in manager when using bladellm
2. centralize instance info management into global_scheduler. Make dispatch_scheduler, migration_scheduler and scaling_scheduler focus on scheduling.
=> [BladeLLM] support dispatch decode instance in manager when using bladellm

requirements/requirements_bladellm.txt
Limit version of some pip packages
1. aiohttp == 3.8.4
2. aiohttp-cors == 0.7.0
aiohttp 3.11.x will cause bladellm engine return incorrect response format
=> [Misc] Specify the version of aiohttp to ensure compatibility with BladeLLM

llumnix/backends/bladellm/llm_engine.py
In the final phase of the migration, in the previous implementation, if an ABORTED_DST occurred, the req_tracker state of the request was mistakenly left unrestored in the add_running_request function.
=> [Bugfix] Fix BladeLLM migration bug in req_tracker

llumnix/backends/bladellm/llm_engine.py, llumnix/backends/bladellm/metrics.py, llumnix/backends/bladellm/scheduler.py
Due to Bladellm returning tokens to Llumnix asynchronously, Llumnix cannot directly delete the server-related information for a request in the request_server_map during handle_abort, handle_drop, or migration free_src_request. Instead, the related information can only be safely removed after the corresponding step's output token has been actually processed in the AsyncBackQueueWrapper.
=> [Bugfix] Fix token failing to return to API server during drop, abort, or migration

llumnix/backends/output_forwarder.py, llumnix/backends/utils.py, llumnix/backends/vllm_v1/async_core.py, llumnix/backends/vllm_v1/core.py, llumnix/backends/vllm_v1/executor.py, llumnix/constants.py, llumnix/entrypoints/api_server_actor.py, llumnix/entrypoints/vllm_v1/api_server.py, llumnix/entrypoints/vllm_v1/arg_utils.py, llumnix/entrypoints/vllm_v1/client.py, llumnix/entrypoints/vllm_v1/dp_manager.py, llumnix/llumlet/llumlet.py, llumnix/ray_utils.py, llumnix/request_output.py, llumnix/scaler.py
Add support of vLLM v1 data parallel serving. Main changes include:
1. Add DPManager component for DP group launching. DPManager will be constructed in Scaler `_auto_scale_up_loop` function.
2. Add AsyncDPEngineCoreProcLlumnix for engine and LlumnixDPClientVLLMV1 for client.
Currently the serving is supported, but fault-tolerant not fully supported yet.
=> [vLLM-v1] Support data parallel of vLLM v1 with DPManager

llumnix/backends/vllm_v1/async_core.py, llumnix/backends/vllm_v1/core.py
Fix two errors:
- TP>1 error because _init_data_parallel not been rewritten, the CUDA_VISIBLE_DEVICES should be removed.
- dpcoord hang because invoke create_engine_config more than one time and set many ports for dpcoord.
=> [vLLM-v1][Bugfix] Fix TP>1 error and dpcoord hang

llumnix/backends/output_forwarder.py, llumnix/backends/vllm_v1/core.py, llumnix/backends/vllm_v1/executor.py, llumnix/entrypoints/vllm_v1/api_server_actor.py, llumnix/entrypoints/vllm_v1/arg_utils.py, llumnix/entrypoints/vllm_v1/dp_manager.py, llumnix/scaler.py
1. Executor will allocate NUM_GPUS_VLLM_V1_GPU_ACTOR GPU for every TP rank now and will cause runtime error. Fix it so that only TP rank0 will get NUM_GPUS_VLLM_V1_GPU_ACTOR GPU and other ranks will get 1 GPU.
2. Fix OutputForwarder bundle_index to dp_rank, default set to 0. 
3. Remove speculative decoding check when check args and add support for it in vLLM v1 backend. It may has no quality assurance for other backend.
4. Add dp_size_local for kvtbackend naming.
5. Fix kv_transfer_config maybe None.
=> [Bugfix][vLLM-v1] Fix TP>1 GPU allocation bug in Executor; Fix OutputForwarder bundle_index bug; Add support for speculative decoding

llumnix/constants.py, llumnix/scaler.py, tests/unit_test/global_scheduler/test_scaler.py
In Scaler's heartbeat loop, once a dp_manager failure is detected, the Scaler will clear the whole unit with calling dp_manager.stop.remote(). Add waiting in the heartbeat loop to avoid it so that the dp_manager can restart and take control of the unit.
=> [Bugfix] Add waiting in Scaler heartbeat loop to avoid clear unit immediately
